config/routes.rb
Rails.application.routes.draw do
  get 'movies/lists'
  get 'movies/bookmarks'
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
resources :bookmarks, only: [:destroy], as: :delete_bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :bookmarks
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

def index
  @bookmarks = Bookmark.all
end

def show
  @bookmark = Bookmark.find(params[:id])
end

def new
  @list = List.find(params[:list_id])
  @bookmark = Bookmark.new
end

def create
  @bookmark = Bookmark.new(bookmark_params)
 if  @bookmark.save
  redirect_to root_path(@bookmark)
 else
  render :new
 end
end

def destroy
  @bookmark = Bookmark.find(params[:id])
  @bookmark.destroy
  redirect_to bookmarks_path, notice: "Bookmark was successfully destroyed"
end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    Rails.logger.debug @list.movies.inspect
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(list_params)
      redirect_to lists_path, notice: "List was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path, notice: "List was successfully destroyed"
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
    @movies = [] if @movies.nil?
  end

def show
  @movie = Movie.find(params[:id])
end

def new
  @movie = Movie.new
end

def create
  @movie = Movie.new(movie_params)
  @movie.save
  redirect_to movie_path(@movie), notice: "Movie was successfully created"
end

def edit
  @movie = Movie.find(params[:id])
end

def update
  @movie = Movie.find(params[:id])
  @movie.update(movie_params)
  redirect_to movie_path(@movie), notice: "Movie was successfully updated"
end

def destroy
  @movie = Movie.find(params[:id])
  @movie.destroy
  redirect_to movies_path, notice: "Movie was successfully destroyed"
end

private

def movie_params
  params.require(:movie).permit(:title, :overview, :poster_url, :rating)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@movie, @list, @bookmark], url: new_list_bookmark_path(@list) do |f| %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.button :submit, "Create Bookmark" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>


    <!-- Le reste du contenu de votre page -->
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<!-- app/views/lists/edit.html.erb -->

<h1>Edit List</h1>

<%= form_with(model: @list, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Update List" %>
  </div>
<% end %>

<%= link_to "Back to Lists", lists_path %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<% @lists.each do |list| %>
  <%= link_to list.name, list %>
<% end %>
<%= link_to "New List", new_list_path, class: "btn btn-success" %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= form_with(model: @list, local: true) do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="movie_show">
    <h2>Add movies to this list:</h2>
    <%= form.select :movie_ids,
                    Movie.all.collect { |m| [m.title, m.id] },
                    {},
                    { multiple: true, size: 5 } %>
  </div>

  <div class="actions">
    <%= form.submit "Create List" %>
  </div>
<% end %>

<%= link_to "Back to Lists", lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<h5>Films dans cette liste :</h2>

<ul>
  <% @list.movies.each do |movie| %>
  <%= render movie %>
  <% all_bookmarks = Bookmark.where(list_id: @list.id) %>
  <% bookmark = all_bookmarks.find{|bookmark| bookmark.movie_id == movie.id} %>
  <%= bookmark.id %>
  <%= link_to "Delete", delete_bookmark_path(bookmark.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>
  <% end %>
</ul>

<%= link_to "Return to all lists", root_path  %>
<%= link_to "Add a bookmark", new_list_bookmark_path(params[:id])  %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= form_with(model: @movie, local: true) do |form| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :overview %>
    <%= form.text_area :overview %>
  </div>

  <div class="field">
    <%= form.label :poster_url %>
    <%= form.text_field :poster_url %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit "Update Movie" %>
  </div>
<% end %>

<%= link_to "Back to Movies", movies_path %>

app/views/movies/new.html.erb
<!-- app/views/movies/new.html.erb -->

<h1>New Movie</h1>

<%= form_with(model: @movie, local: true) do |form| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :overview %>
    <%= form.text_area :overview %>
  </div>

  <div class="field">
    <%= form.label :poster_url %>
    <%= form.text_field :poster_url %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit "Create Movie" %>
  </div>
<% end %>

<%= link_to "Back to Movies", movies_path %>

app/views/movies/show.html.erb
<!-- app/views/movies/show.html.erb -->

<h1>Movie Details</h1>

<p><strong>Title:</strong> <%= @movie.title %></p>
<p><strong>Overview:</strong> <%= @movie.overview %></p>
<p><strong>Poster URL:</strong> <%= @movie.poster_url %></p>
<p><strong>Rating:</strong> <%= @movie.rating %></p>

<%= link_to "Edit", edit_movie_path(@movie) %> |
<%= link_to "Back to Movies", movies_path %> |
<%= link_to "Delete", @movie, method: :delete, data: { confirm: "Are you sure?" } %>